services:
  backend-testing:
    container_name: backend-testing
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: .
      target: test
    volumes:
      - .:/src

