services:
  frontend:
    image: nosebook-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8000:8000

  backend:
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    build:
      context: .
      target: final
    environment:
      - POSTGRES_DB=nosebook
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - APP_ENV=$APP_ENV
    develop:
      watch:
        - action: rebuild
          path: ./src
    ports:
      - 8080:8080
    healthcheck:
      test: curl http://backend:8080/ping --fail
      interval: 10s
      timeout: 2s
      retries: 3

  db:
    image: nosebook-postgres
    container_name: db
    restart: always
    user: postgres
    # command: ["postgres", "-c", "log_statement=all"]
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=nosebook
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5

secrets:
  db-password:
    file: db-password.txt

