global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: nosebook
    static_configs:
      - targets: ["backend:8080"]
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["db-prometheus-exporter:9187"]

