#!/bin/bash

docker run --rm -d \
  -p 9090:9090 \
  --name prometheus \
  --network back_default \
  -v ./prometheus.yml:/etc/prometheus/prometheus.yml \
  -v prometheus-data:/prometheus \
  prom/prometheus
